### ISSUE TITLE
Hardcoded scales, rotations and offsets for stones

### ISSUE THREAD

**Issue by f-escarate** [AzcarGabriel/jachkar-museum#2]
There are 3 methods that have hardcoded information used when a Jachkar spawns. Those methods are in the class `Assets/Scripts/Helpers/StoneSpawnHelper.cs`. I would like to change that and write the information directly it the AssetBundles for stones metadata, but i am worried about break something on production.

**Comment by AzcarGabriel** [comment]
Hello,

That's a great idea. If you add the new information to the metadata, upload the updated asset to the server and **do not** update a new compilation of the code, the old code running in production will still looking for the hardcoded values, so it will be fine. The new values at the metadata asset will be data that won't be used by the old code.

Gabriel

**Comment by f-escarate** [comment]
Thanks for the reply! 🙏 I'm going a create a branch for that.

Also i have a question with:
> do not update a new compilation of the code, the old code running in production will still looking for the hardcoded values, so it will be fine.

In case that would be necessary to add new stones (with their translation properties), then the new compilation should be updated. This could broke something?

Felipe

**Comment by AzcarGabriel** [comment]
If you add new stones without updating the compilation, the production code will spawn this new stones using the old hardcoded rules so maybe it would be a deficient spawn, but it will not break (I mean it won't stop working, but will be a spawned stone with wrong translations). Of course this will not be a problem if you update the production compilation to use the new data.
